import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/shadcn-ui/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					`bg-white dark:bg-slate-800 text-slate-800 dark:text-white min-h-[100vh]`
				)}
			>
				{children}
			</body>
		</html>
	);
}
